Iter15
Azcarot/Metrics pull request #15
Opened 2024-01-30 16:17 UTC by Azcarot

2024-01-31 11:47 UTC, tmvrus requested changes
слишком много паники

2024-01-31 11:47 UTC, tmvrus commented on internal/handlers/jsonhandler.go
> +			fmt.Println("errorHere3")
некрасиво

2024-01-31 11:47 UTC, tmvrus commented on internal/handlers/posthandler.go
> +}
у этой ф-и очень странный дизайн:
- паниковать она не должна никогда: если случается ошибка, панику уронит весь воркер и никаких следующих попыток не будет
- неясно для какой цели пишется в канал, снаружи это никто не читает
- повторное закрытие канала лаже в разных горутинах ведет к панике
- запись в уже закрытый канал, точно так же, ведет к панике: вполне вероятно что запрос завершится раньше другого и канал будет закрыт, кстати если случится паника - то не будет закрыт
- resp.Body.Close() вызывается несколько раз, притом, без всякого смысла - потому что внутри PostJSONMetrics метод уже вызывался
- сама структура вызывает вопрос, по сути все что нужно делать что то типа:
```
for i := 0; i < sendAttempts; i++ {
		resp, err := PostJSONMetrics()
		if err != nil  {
		// sleep
                 }
                 return 
}
```
в любом случае текущая реализация с паниками - работать не будет

2024-01-31 11:47 UTC, tmvrus commented on internal/handlers/posthandler.go
>  		panic(fmt.Sprintf("cannot post %s ", b))
никакой паники тут быть не должно: снаружи она не ловится а сама ф-я может вернуть ошибку

2024-01-31 11:47 UTC, tmvrus commented on internal/handlers/posthandler.go
> +		defer res.Body.Close()
если client.Do(resp) вернет ошибку, то res будет nil и попытка закрыть тело ответа приведет к панике

2024-01-31 13:35 UTC, Azcarot commented on internal/handlers/jsonhandler.go
> +			fmt.Println("errorHere3")
Убрал

2024-01-31 13:35 UTC, Azcarot commented on internal/handlers/posthandler.go
> +}
Убрал паники, но закрытие тела запроса оставил - без них не проходит static test

2024-01-31 13:35 UTC, Azcarot commented on internal/handlers/posthandler.go
>  		panic(fmt.Sprintf("cannot post %s ", b))
Убрал

2024-01-31 13:35 UTC, Azcarot commented on internal/handlers/posthandler.go
> +		defer res.Body.Close()
Убрал панику

2024-01-31 15:17 UTC, tmvrus commented on internal/handlers/posthandler.go
> +func PostJSONMetrics(b []byte, a string, f agentconfigs.AgentData) (*http.Response, error) {
я тебе предлагаю задуматься, зачем вообще возвращать отсюда *http.Response, может можно вообще ничего не возвращать? или возвращать []byte который  прислали в ответе?

2024-01-31 15:17 UTC, tmvrus requested changes
все еще 2 панике в коде, которые ничем не обоснованы

2024-02-02 07:19 UTC, Azcarot commented on internal/handlers/posthandler.go
> +func PostJSONMetrics(b []byte, a string, f agentconfigs.AgentData) (*http.Response, error) {
Да, я его не обрабатываю, возвращать бессмысленно

2024-02-03 20:09 UTC, tmvrus requested changes

2024-02-03 20:09 UTC, tmvrus commented on internal/middleware/hashsha.go
> +						panic(err)
опять паника

2024-02-05 14:00 UTC, Azcarot commented on internal/middleware/hashsha.go
> +						panic(err)
Переделал на 500 ошибку

2024-02-05 18:55 UTC, tmvrus approved these changes

2024-02-06 06:24 UTC, merged