Iter23
Azcarot/Metrics pull request #23
Opened 2024-04-25 09:02 UTC by Azcarot

2024-05-03 15:38 UTC, tmvrus requested changes

2024-05-03 15:38 UTC, tmvrus commented on internal/handlers/posthandler.go
> +			log.Fatal(err)
а может проверить, вдруг там нет ошибки?

2024-05-03 15:38 UTC, tmvrus commented on internal/handlers/posthandler.go
> +			log.Fatal(err)
а как ты провеял код которые падает в любом случае?

2024-05-03 15:38 UTC, tmvrus commented on internal/middleware/decypher.go
> +				http.Error(w, err.Error(), http.StatusInternalServerError)
после ошибки код продолжит работать

2024-05-03 15:38 UTC, tmvrus commented on internal/serverconfigs/serverflagsandenv.go
> +		fmt.Println(fileData)
fmt для логирования не предназначен

2024-05-03 16:01 UTC, Azcarot commented on internal/middleware/decypher.go
> +				http.Error(w, err.Error(), http.StatusInternalServerError)
Да, поставил возврат

2024-05-03 16:01 UTC, Azcarot commented on internal/serverconfigs/serverflagsandenv.go
> +		fmt.Println(fileData)
Убрал, забыл при дебаге

2024-05-03 16:02 UTC, Azcarot commented on internal/handlers/posthandler.go
> +			log.Fatal(err)
Поправил, перепроверил, немного переделал gracefullshutdown для агента - иначе блочилась горутина

2024-05-05 20:02 UTC, tmvrus approved these changes

2024-05-05 20:02 UTC, tmvrus commented on cmd/agent/main.go
> +	shutdown := make(chan bool)
обычно все же используют chan struct{}

2024-05-05 20:39 UTC, merged