Iter25
Azcarot/Metrics pull request #25
Opened 2024-05-10 17:55 UTC by Azcarot

Теперь шифрую данные разбивая их по чанкам чтобы не хранить огромные ключи, добавил поддержку grpc на одном порту с http через мультплексор, для grpc реализовал один метод - UpdateMetric - обновление метрик по отдельности (не батчами)

2024-05-14 12:07 UTC, tmvrus requested changes

2024-05-14 12:07 UTC, tmvrus commented on cmd/proto/metrics.proto
> +  string mtype = 2; // тип метрики
для ограниченого числа значений  в grpc есть num-тип
https://protobuf.dev/programming-guides/proto3/#enum

2024-05-14 12:07 UTC, tmvrus commented on cmd/server/main.go
> +	// server := &http.Server{
закоменченного кода в рабочем проекте быть не должно, это дурной тон

2024-05-14 12:07 UTC, tmvrus commented on cmd/server/main.go
> +	Flags = flag
зачем понадобилось делать две переменных?

2024-05-14 12:07 UTC, tmvrus commented on cmd/server/main.go
> +	// server.ListenAndServe()
закоменченный код

2024-05-14 12:07 UTC, tmvrus commented on cmd/proto/metrics.proto
> +  string error = 1; // ошибка
а зачем пихать сюда ошибку если для нее уже предусмотрено место в сигнатуре метода?

2024-05-14 12:07 UTC, tmvrus commented on internal/handlers/posthandler.go
> +		log.Fatal(err)
сурово, а если хост не поддериживает udp то можно всего агента ронять?

2024-05-14 12:07 UTC, tmvrus commented on internal/middleware/checkip.go
> +			_, inet, err := net.ParseCIDR(flag.FlagSubnet)
парсинг можно было сделать один раз при старте приложения или создании мидлвари

2024-05-14 12:07 UTC, tmvrus commented on cmd/agent/main.go
> +			log.Fatal(err)
если произошла сетевая ошибка то нужно уронить все приложение ?

2024-05-14 12:07 UTC, tmvrus commented on internal/proto/protoFuncs.go
> +				if ok {
а если не ok то что?

2024-05-14 15:11 UTC, Azcarot commented on cmd/server/main.go
> +	// server := &http.Server{
Убрал

2024-05-14 15:11 UTC, Azcarot commented on cmd/server/main.go
> +	Flags = flag
Забыл все перенести в одну, теперь только одна переменная

2024-05-14 15:11 UTC, Azcarot commented on cmd/server/main.go
> +	// server.ListenAndServe()
Убрал

2024-05-14 15:13 UTC, Azcarot commented on internal/handlers/posthandler.go
> +		log.Fatal(err)
Теперь возвращаю nil

2024-05-14 15:17 UTC, Azcarot commented on cmd/agent/main.go
> +			log.Fatal(err)
Теперь не роняем приложение

2024-05-14 15:19 UTC, Azcarot commented on internal/proto/protoFuncs.go
> +				if ok {
теперь отвечаем ошибкой

2024-05-14 16:33 UTC, Azcarot commented on internal/middleware/checkip.go
> +			_, inet, err := net.ParseCIDR(flag.FlagSubnet)
вынес в создание миддлвари

2024-05-14 16:34 UTC, Azcarot commented on cmd/proto/metrics.proto
> +  string error = 1; // ошибка
убрал

2024-05-14 16:34 UTC, Azcarot commented on cmd/proto/metrics.proto
> +  string mtype = 2; // тип метрики
теперь использую num

2024-05-16 06:53 UTC, tmvrus approved these changes

2024-05-16 07:00 UTC, merged