Iter5
Azcarot/Metrics pull request #5
Opened 2023-12-07 16:38 UTC by Azcarot

2023-12-11 08:55 UTC, tmvrus requested changes
Есть замечания.

2023-12-11 08:55 UTC, tmvrus commented on cmd/agent/main.go
> +		time.Sleep(time.Duration(agentData.pollint) * time.Second)
на каждой итерации код будет вычислять `time.Duration(agentData.pollint) * time.Second`, вычисление можно сделать один раз  перед началом цикла

2023-12-11 08:55 UTC, tmvrus commented on cmd/agent/main.go
> +		}
по условию инкремента, отправка данных на сервер должна происходить по интервалу, данное условие некорректно. для того что бы запустить независимо сбор и отправку метрк, хорошо подойдут ф-и time.AfterFunc, time.Interval, либо проверять что с момента последней отправки на сервер прошло `reportint` времени

2023-12-11 08:55 UTC, tmvrus commented on cmd/types/types.go
> +	}
строки "gauge" и "counter" повсеместно встречаются в коде, это хорошо повод сделать их константами

2023-12-11 08:55 UTC, tmvrus commented on cmd/agent/measure/measure_test.go
> +	}}
табличный тест из 1 элемента выглядит избыточным, назначение такие тестов как раз в том, что бы в одном месте описать несколько кейсов

2023-12-11 08:55 UTC, tmvrus commented on cmd/server/handlers/gethandler.go
> +	if len(chi.URLParam(req, "name")) != 0 && len(chi.URLParam(req, "value")) != 0 && len(chi.URLParam(req, "type")) != 0 {
если код не зайдет в это условие, клиенту вернется 200 OK
вряд ли это корректное поведение, рекомендую переписать весь хендлер уменьшив вложеность кода, это повысит читаемость
https://habr.com/ru/articles/15479/

2023-12-11 08:55 UTC, tmvrus commented on cmd/server/main.go
> +	}
http.ListenAndServe всегда возвращает ошибку, это написано в документации к методу, таким образом этот код всегда будет завершатся с паникой

2023-12-11 08:55 UTC, tmvrus commented on cmd/server/handlers/gethandler_test.go
> +}
у этого теста есть важный недостаток - он использует свой собственный конструктор для роутера, таким образом в коде есть два одинаковых маршрута - один рабочий, но не тестируемый, второй тестируемый но не рабочий

2023-12-11 15:29 UTC, Azcarot commented on cmd/agent/main.go
> +		time.Sleep(time.Duration(agentData.pollint) * time.Second)
Убрал, рассчитываю 1 раз

2023-12-11 15:29 UTC, Azcarot commented on cmd/agent/main.go
> +		}
Переделал на использование time.AfterFunc

2023-12-11 15:30 UTC, Azcarot commented on cmd/types/types.go
> +	}
Описал типы константами

2023-12-11 15:30 UTC, Azcarot commented on cmd/agent/measure/measure_test.go
> +	}}
переделал на единичный тест

2023-12-11 15:30 UTC, Azcarot commented on cmd/server/handlers/gethandler.go
> +	if len(chi.URLParam(req, "name")) != 0 && len(chi.URLParam(req, "value")) != 0 && len(chi.URLParam(req, "type")) != 0 {
Переписал

2023-12-11 15:30 UTC, Azcarot commented on cmd/server/main.go
> +	}
Убрал панику

2023-12-11 15:31 UTC, Azcarot commented on cmd/server/handlers/gethandler_test.go
> +}
Переписал тест на использование рабочего роутера

2023-12-12 13:48 UTC, tmvrus approved these changes

2023-12-12 13:50 UTC, merged