Iter9
Azcarot/Metrics pull request #9
Opened 2024-01-04 21:30 UTC by Azcarot

2024-01-09 19:40 UTC, tmvrus requested changes
все собрано в кучу и хендлеры и мидлвари, работа с файлами и конфигами.
Такую работу я не приму.
Минимально:
- в cmd должен остаться только agent и server
- код в cmd должен оперировать только конфигами и запускать приложение
- storage и handler должны переехать в internal
- никаких "протекающих абстракций" быть не должно - каждый слой/пакет должен отвечать за свои ф-и (SOLID)

2024-01-09 19:40 UTC, tmvrus commented on cmd/server/handlers/gethandler.go
>  	r.Use()
r.Use как раз нужен что бы добавлять middleware, их можно добавить в эту ф-ю один раз и не добавлять для каждого хендлера

2024-01-09 19:40 UTC, tmvrus commented on cmd/storage/memstorage.go
> +func (m *MemStorage) StoreMetrics(n string, t string, v string) error {
n string, t string, v string
можно переписать как
n, t, v string

2024-01-10 17:09 UTC, Azcarot commented on cmd/storage/memstorage.go
> +func (m *MemStorage) StoreMetrics(n string, t string, v string) error {
Переделал

2024-01-10 17:09 UTC, Azcarot commented on cmd/server/handlers/gethandler.go
>  	r.Use()
Не знал, теперь использую

2024-01-11 18:56 UTC, tmvrus approved these changes

2024-01-12 06:20 UTC, merged